def0:
  create-pre:
    - '{$quality:random:group:品质}'
  id: "{random:group:{map:quality}材质}"
  name: "{map:quality}的 神木"
  lore:
    - ''
    - '&f攻击力+ &b{eval:{random:group:{map:quality}攻击} * {papi:%player_level%def:0} * 0.5}'
    - '强度值 {func:format({random:int:0-20})}'
    - ''
    - '&c来源: &f{papi:%player_name%def:0}'
  item-flags:
    - HIDE_ENCHANTS
    - HIDE_ATTRIBUTES
    - HIDE_UNBREAKABLE
    - HIDE_DESTROYS
    - HIDE_PLACED_ON
    - HIDE_POTION_EFFECTS
  nbt:
    max-durability: 100
    attributes:
      - '物理攻击: 100'
  actions:
    - $e: item consume
      action:
        - |-
          attribute add def0 5000 "攻击力 +10" they -"@self"

proxy-def0:
  g: proxy
  id: def0
  vars:
    quality: 普通

drop-table:
  g: group
  items:
    - def0 1 1