def0:
  create-pre:
    - '{$quality:random:group:品质}'
  id: "{random:group:{map:quality}材质}"
  name: "{map:quality}的 神木"
  lore:
    - ''
    - '&f攻击力+ &b{eval:{random:group:{map:quality}攻击} * {papi:%player_level%} * 0.5}'
    - '强度值 {func:format({random:int:0-20})}'
    - ''
    - '&c来源: &f{papi:%player_name%}'
    - ''
    - '{random:group:描述}'