options:
  random-split-char: '#'
  decimal-format: '#.##'
  time-format: 'yyyy-MM-dd HH:mm:ss'
  damage-effect-limit: true
  operator-add: '+'
  operator-take: '-'
  original: true
  damage-cause:
    - ENTITY_ATTACK
    - ENTITY_SWEEP_ATTACK
    - PROJECTILE
  skip-strings:
    - 'prefix 装备效果'
    - 'prefix 套装效果'
    - 'suffix xxx'
    - 'regex \[[0-9]+].*'
  sell:
    title: '物品回收'
    keyword:
      - '出售价格'
    slots: [ 10,11,12,13,14,15,16,19,20,21,22,23,24,25,26 ]
    template-s:
      id: STONE
      slots: [ 10 ]
      lore:
        - 点击回收
  condition:
    level:
      keyword:
        - '使用等级'
    time:
      keyword:
        - '使用期限'
    occupation:
      keyword:
        - 职业需要
      pattern:
        - 战士 oa.occ.战士
        - 肉盾 oa.occ.肉盾
        - 职业 oa.occ.职业
    slot:
      keyword:
        - '物品类型'
      pattern:
        Hand:
          - '主手'
        OffHand:
          - '副手'
        Helmet:
          - '头盔'
        BreastPlate:
          - '胸甲'
        Gaiter:
          - '护腿'
        Boot:
          - '鞋子'
        InventorySlot:
          - '10 戒指'
          - '11 项链'
  remotes:
    - BOW

attributes:
  - Damage
  - BloodSucking
  - Crit
  - JumpDamage
  - Hit
  - Armor
  - Dodge
  - Rebound
  - ExpAddon
  - HealthRecovery
  - Health
  - MoveSpeed
  - Special
  - AttackSpeed
  - ArmorBreak
  - Power
