options:
  random-split-char: '#'
  decimal-format: '#.##'
  time-format: 'yyyy-MM-dd HH:mm:ss'
  operator-add: '+'
  operator-take: '-'
  original: true
  sell:
    title: '物品回收'
    keyword:
      - '出售价格'
    slots: [ 10,11,12,13,14,15,16,19,20,21,22,23,24,25,26 ]
    layout:
      - '#########'
      - '#iiiiiii#'
      - '#iiiiiii#'
      - '####s####'
    template-#: 'sell-#'
    template-s: 'sell-s'
  condition:
    level:
      keyword:
        - '使用等级'
    time:
      keyword:
        - '使用期限'
    occupation:
      keyword:
        - 职业需要
      pattern:
        - 战士 oa.occ.战士
        - 肉盾 oa.occ.肉盾
        - 职业 oa.occ.职业
    slot:
      keyword:
        - '物品类型'
      pattern:
        Hand:
          - '主手'
        OffHand:
          - '副手'
        Helmet:
          - '头盔'
        BreastPlate:
          - '胸甲'
        Gaiter:
          - '护腿'
        Boot:
          - '鞋子'
        InventorySlot:
          - '10 戒指'
          - '11 项链'
  remotes:
    - BOW

attributes:
  - Damage
  - BloodSucking
  - Crit
  - JumpDamage
  - Hit
  - Armor
  - Dodge
  - Rebound
  - ExpAddion
  - HealthRecovery
  - Health
  - MoveSpeed
  - Special
  - AttackSpeed
  - ArmorBreak
  - RangeDamage
  - ShieldRecovery
  - Shield
  - Power
  - DirectionDamage
  - AttackDistance