script:
  javascript-def0:
    types: [ ATTACK ]
    value-type: SINGLE
    combat-power: 1.0
    keywords:
      - '真实伤害'
damage-handler: |-
  if(openAPI.hasLabel("@Crit")) {
    openAPI.sendTitle(openAPI.attacker,'','                 §c-§o' + openAPI.totalDamage.toFixed(2),15,30,15)
  } else {
    openAPI.sendTitle(openAPI.attacker,'','                 §f-§o' + openAPI.totalDamage.toFixed(2),15,30,15)
  }
