script:
  javascript-def0:
    types: ATTACK
    value-type: SINGLE
    combat-power: 1.0
    keywords:
      - '真实伤害'
damage-handler: |-

  if(openAPI.hasLabel("@Crit")) {
    openAPI.attacker.sendTitle('','                 §c-§o' + openAPI.totalDamage,15,30,15)
  } else {
    openAPI.attacker.sendTitle('','                 §f§o-' + openAPI.totalDamage,15,30,15)
  }
