default0:
  id: {random:group:剑士}
  lore:
    - ''
    - '攻击力: {eval:{random:double:10-20}*{papi:%player_level%}} - {random:double:20-40}'
    - '攻击力: {计算:{随机:小数:10到20}*{变量:%player_level%}} - {随机:小数:20到40}'
    - '职业: '

剑士:
  - '201'
  - '202'
  - '203'
  - '{random:int:{random:group:低级剑士}-40}'
低级剑士:
  - '{random:int:20-30}'
  - '{random:int:40-50}'